export const types = {
    UPDATE_AVATAR:         'UPDATE_AVATAR',
    FILL_PROFILE:          'FILL_PROFILE',
    CLEAR_PROFILE:         'CLEAR_PROFILE',
    UPDATE_NAME_ASYNC:     'UPDATE_NAME_ASYNC',
    UPDATE_AVATAR_ASYNC:   'UPDATE_AVATAR_ASYNC',
    UPDATE_PASSWORD_ASYNC: 'UPDATE_PASSWORD_ASYNC'
};
